package com.distalgo.saga.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

// because added Lombok as a dependency, don't need to write getter and setter manually
@Data
@AllArgsConstructor
@NoArgsConstructor
public class OrderRequestDTO {
    // when purchasing the order, all these fields must be passed
    private Integer userID; // used to validate the available amount left for the user in payment service
    private Integer ticketedEventID; // used to validate seats left for the event in inventory service
    private Integer seats; // number of seats to reserve
    private Integer amount; // total amount, cash-wise
    private Integer orderID; // autogenerated through the system
}
